관통프로젝트/PJT06/06_pjt_kimminchae/accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('<int:user_pk>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

관통프로젝트/PJT06/06_pjt_kimminchae/boards/urls.py
from django.urls import path
from . import views

app_name="boards"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'), 
    path('<int:pk>/like/', views.like, name='like'),
    path('<int:pk>/update/', views.update, name='update'),   
    path('<int:board_pk>/comment/', views.comment, name='comment'),
    path('<int:board_pk>/comment/<int:comment_pk>/', views.comment_detail, name='comment_detail'),
    path('comment/<int:comment_pk>/', views.create_reply, name='create_reply'),
]

관통프로젝트/PJT06/06_pjt_kimminchae/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('accounts/', include('accounts.urls')),
]

관통프로젝트/PJT06/06_pjt_kimminchae/templates/_navbar.html
<div>
  {% if user.is_authenticated %}
  <h2 style = "display: flex; justify-content: space-between;">Hello, {{user.username}} 
    <a href="{% url "accounts:logout" %}" class="btn btn-light">로그아웃</a></h2> 
  {% else %}
  <h2 style="display: flex; justify-content: space-between;">로그인을 해주세요. 
    <span>
    <a class="btn btn-light" href="{% url 'accounts:login' %}">로그인</a>
    <a class="btn btn-light" href="{% url 'accounts:signup' %}">회원 가입</a>
  </span>
</h2>
  {% endif %}
</div>

<hr>
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'boards:index' %}">메인 페이지</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'accounts:profile' user.pk %}">프로필 페이지</a>
        </li>
        {% endif %}
      </ul>
      <ul class="navbar-nav">
        
          {% comment %} <li>
            <span class="nav-link">{{ user }}</span>
          </li>
          <li>
            <a href="{% url "accounts:logout" %}" class="nav-link">로그아웃</a>
          </li> {% endcomment %}
          {% comment %} <li>
            <a class="nav-link" aria-current="page" href="{% url 'accounts:login' %}">로그인</a>
          </li>
          <li>
            <a class="nav-link" aria-current="page" href="{% url 'accounts:signup' %}">회원 가입</a>
          </li> {% endcomment %}
        
      </ul>
    </div>
  </div>
</nav>

관통프로젝트/PJT06/06_pjt_kimminchae/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <div class="mt-3 container">
    <div class="mt-3 mb-4">
      {% include '_navbar.html' %}
    </div>
    <div class="mb-5">
      {% block content %}
      {% endblock content %}
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>