DB/Day_3/db_ws_3_2/restaurant_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('restaurants/', include('restaurants.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

DB/Day_3/db_ws_3_2/restaurants/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'restaurants'
urlpatterns = [
    path('', views.index, name = 'index'), 
    path('create/', views.create, name = 'create'),
    path('<int:restaurant_pk>/', views.detail, name = "detail"),
    path('<int:restaurant_pk>/create_menu/', views.create_menu, name='create_menu'),
    path('<int:restaurant_pk>/menus/<int:menu_pk>/update/', views.update_menu, name = 'update_menu'),
]

DB/Day_3/db_ws_3_2/restaurants/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=20)
    image = models.ImageField(blank = True)
    def __str__(self):
        return self.name

class Restaurant(models.Model):
    catrgory = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    descriptions = models.TextField()
    address = models.CharField(max_length=200)
    opening_time = models.TimeField()
    closing_time = models.TimeField()

class Menu(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    is_vegan = models.BooleanField()
    

DB/Day_3/db_ws_3_2/restaurants/forms.py
from .models import Restaurant, Menu
from django import forms

class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = '__all__'
        widgets = {
            'opening_time': forms.TimeInput(attrs={'type': 'time'}),
            'closing_time': forms.TimeInput(attrs={'type': 'time'})
        }


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ('name', 'price', 'is_vegan',)
        
class MenuUpdateForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ('price', 'is_vegan',)

DB/Day_3/db_ws_3_2/restaurants/views.py
from django.shortcuts import render, redirect
from .models import Restaurant, Category, Menu
from .forms import RestaurantForm, MenuForm, MenuUpdateForm

# Create your views here.
def index(request):
    restaurants = Restaurant.objects.all()
    category = Category.objects.all()
    context = {
        'restaurants':restaurants,
        'category': category,
    }
    return render(request, 'restaurants/index.html', context)

def create(request):
    if request.method == 'POST':
        form = RestaurantForm(request.POST)
        if form.is_valid():
            restaurant = form.save()
            return redirect('restaurants:detail', restaurant.pk)
    form = RestaurantForm()
    context = {
        'form': form,
    }
    return render(request, 'restaurants/create.html', context)

def detail(request, restaurant_pk):
    restaurant = Restaurant.objects.get(pk = restaurant_pk)
    category = Category.objects.get(pk=restaurant.catrgory_id)
    form = MenuForm()
    menu = Menu.objects.filter(restaurant = restaurant.pk)
    context = {
        'form': form,
        'category':category,
        'restaurant': restaurant,
        'menu': menu,
    }
    return render(request, 'restaurants/detail.html', context)

def create_menu(request, restaurant_pk):
    restaurant = Restaurant.objects.get(pk=restaurant_pk)
    menu_form = MenuForm(request.POST)
    if menu_form.is_valid():
        menu = menu_form.save(commit = False)
        menu.restaurant = restaurant
        menu.save()
        return redirect('restaurants:detail', restaurant.pk)
    context = {
        'menu_form': menu_form,
        'restaurant': restaurant,
        
    }
    return render(request, 'restaurants:detail', context)

def update_menu(request, restaurant_pk, menu_pk):
    restaurant = Restaurant.objects.get(pk = restaurant_pk)
    menu = Menu.objects.get(pk = menu_pk)
    if request.method == 'POST':
        menu_update_form = MenuUpdateForm(request.POST, instance = menu)
        if menu_update_form.is_valid():
            menu = menu_update_form.save()
            return redirect('restaurants:detail', restaurant.pk)
    else:
        menu_update_form = MenuUpdateForm()
    context = {
        'menu_update_form': menu_update_form,
    }
    return render(request, 'restaurants/update.html', context)

DB/Day_3/db_ws_3_2/restaurants/templates/restaurants/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
  <h1>신규 레스토랑 등록</h1>
  <form action="{% url "restaurants:create" %}" method = "POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class = "form-control" type="submit" value = "등록">
  </form>
  <a href="{% url "restaurants:index" %}">[돌아가기]</a>
{% endblock content %}

DB/Day_3/db_ws_3_2/restaurants/templates/restaurants/detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>레스토랑 상세 정보</h1>
  <p>등록 번호 : {{restaurant.pk}}</p>
  <p>종류 : {{category}}</p>
  <p>이름 : {{restaurant.name}}</p>
  <p>주소 : {{restaurant.address}}</p>
  <p>여는 시간 : {{restaurant.opening_time}}</p>
  <p>닫는 시간 : {{restaurant.closing_time}}</p>
  <hr>
  <p>{{category}}</p>
  <hr>
  <h3>신규 메뉴 등록</h3>
  <form action="{% url "restaurants:create_menu" restaurant.pk %}" method = "POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value = "메뉴등록">
  </form>
  <hr>
  <h3>전체 메뉴 목록</h3>
  <ul>
  {% for m in menu %}
  <li>이름 : {{m.name}}</li>
  <li>가격 : {{m.price}}</li>
  <a href="{% url "restaurants:update_menu" restaurant.pk m.pk %}">[메뉴 정보 수정]</a>
  {% endfor %}
</ul>
  <a href="{% url "restaurants:index" %}">[돌아가기]</a>
{% endblock content %}

DB/Day_3/db_ws_3_2/restaurants/templates/restaurants/index.html
{% extends "base.html" %}
{% block content %}
  <h1>레스토랑 전체 목록</h1>
  <a href="{% url "restaurants:create" %}">[신규 레스토랑 등록]</a>
  <ul>
    {% for restaurant in restaurants %}
    <a href="{% url "restaurants:detail" restaurant.pk %}">
    <li>이름 : {{restaurant.name}}</li>
    {% for cat in category %}
    {% if cat.pk == restaurant.catrgory_id %}
      {% if cat.image %}
       <img style = "height: 300px ; width :300px;"" src="{{cat.image.url}}">
      {% else %}
      <p>이미지가 없습니다.</p>
        <li>종류 : {{cat.name}}</li>
      {% endif %}
    <li>보유 중인 메뉴 수 : {{restaurant.menu_set.all|length}}</li>
    {% endif %}
    {% endfor %}
    </a>
    <hr>
    {% endfor %}
     
  </ul>
{% endblock content %}

DB/Day_3/db_ws_3_2/restaurants/templates/restaurants/update.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>메뉴 정보 수정 페이지</h1>
  <form method = "POST">
    {% csrf_token %}
    {% bootstrap_form menu_update_form %}
    <input type="submit" value = "정보수정">
  </form>
  <a href="{% url "restaurants:index" %}">[돌아가기]</a>
{% endblock content %}