DB/Day_4/db_ws_4_a/diaries/urls.py
from django.urls import path
from . import views


app_name = 'diaries'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:diary_pk>/comments/', views.comments_create, name='comments_create'),
    path('comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
]

DB/Day_4/db_ws_4_a/diaries/models.py
from django.db import models

# Create your models here.
class Diary(models.Model):
    content = models.CharField(max_length=125)
    picture = models.ImageField(blank=True, upload_to='diary/%y/%b/%a')
    created_at = models.DateTimeField(auto_now_add=True)

class Comment(models.Model):
    diary = models.ForeignKey(Diary, on_delete=models.CASCADE)
    content = models.CharField(max_length=125)
    created_at = models.DateTimeField(auto_now_add=True)

DB/Day_4/db_ws_4_a/diaries/forms.py
from django import forms
from .models import Diary, Comment


class DiaryForm(forms.ModelForm):

    class Meta:
        model = Diary
        fields = '__all__'

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        # fields = ('content',)
        exclude = ('diary',)

DB/Day_4/db_ws_4_a/diaries/views.py
from django.shortcuts import render, redirect
from .models import Diary, Comment
from .forms import DiaryForm, CommentForm

# Create your views here.
def index(request):
    diaries = Diary.objects.all()
    comment_form = CommentForm()
    context = {
        'diaries': diaries,
        'comment_form': comment_form
    }
    return render(request, 'diaries/index.html', context)

def create(request):
    if request.method == 'POST':
        form = DiaryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('diaries:index')
    else:
        form = DiaryForm()
    context = {
        'form': form
    }
    return render(request, 'diaries/create.html', context)

def comments_create(request, diary_pk):
    diary = Diary.objects.get(pk=diary_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.diary = diary
            comment.save()
    return redirect('diaries:index')

def comments_delete(request, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()
    return redirect('diaries:index')

DB/Day_4/db_ws_4_a/diaries/templates/diaries/index.html
{% extends "base.html" %}

{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static "diaries/style.css" %}">
{% endblock style %}

{% block content %}
  <h1>일기장</h1>
  <a href="{% url "diaries:create" %}">[일기 쓰기]</a>
  <ul class="diaries">
    {% for diary in diaries %}
    <article class="diaries-main">
      <li>
        <p>작성일 : {{ diary.created_at }}</p>
        {% if diary.picture %}
          <img src="{{ diary.picture.url }}" alt="{{ diary.picture }}">
        {% else %}
          <img src="{% static "diaries/default.png" %}" alt="{{ diary.picture }}">
        {% endif %}
        <p>{{ diary.content }}</p>
      </li>
      
      <section class="diaries-comment">
        <ul>
          {% for comment in diary.comment_set.all %}
            <li>
              <span>{{ comment.pk }} | {{ comment.content }}</span>
              <form action="{% url "diaries:comments_delete" comment.pk %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="댓글 삭제">
              </form>
            </li>
          {% empty %}
            <li>
              <span>첫 번째 댓글을 작성해보세요.</span>
            </li>
          {% endfor %}
        </ul>
        <form action="{% url "diaries:comments_create" diary.pk %}" method="POST">
          {% csrf_token %}
          {{ comment_form.as_p }}
          <input type="submit" value="댓글 생성">
        </form>
      </section>
      
    </article>
    {% empty %}
      <li>아직 작성한 일기가 없습니다.</li>
    {% endfor %}
  </ul>
{% endblock content %}